# Generated by Django 5.0.7 on 2024-09-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='original/')),
                ('compressed_image', models.ImageField(blank=True, null=True, upload_to='compressed/')),
            ],
        ),
    ]
